.github/ISSUE_TEMPLATE/considering-report-template.md
.github/ISSUE_TEMPLATE/task-report-template.md
packages/client/package.json
packages/client/src/hooks/useChat.ts
packages/server/.eslintrc.json
packages/server/index.ts
packages/server/loaders/express.ts
packages/server/loaders/index.ts
packages/server/loaders/socket.ts
packages/server/loaders/sockets/chat.ts
packages/server/loaders/sockets/index.ts
packages/server/package.json
yarn.lock

<br/>
- roomId 기반 사용자 소켓  RoomSpace로 분리 (query로 전달)
- loaders 디렉토리 내 서버 초기 설정 위한 loader 구현 (Express, Socket)
- 현재 루트(/) Namespace로 소켓 연결 (후에 채널별 Namespace 사용)
- useChat 커스텀 훅 통해서 소켓 연결/해제 및 이벤트 설정
<br/>
- middleware로 소켓 에러 처리
<br/>
- task issues: Resolves #2, #3

[TASK] 소켓 설정

---

packages/domain/types/vote.ts
packages/server/loaders/sockets/game.ts
packages/server/loaders/sockets/index.ts
packages/server/loaders/sockets/vote.ts

<br/>
<br/>
- task issues: Resolves #11

[TASK] 서버에서 투표 처리 기능 구현

---

packages/client/package.json
packages/client/src/components/Message/ChatMsg.tsx
packages/client/src/containers/ChatContainer.tsx
packages/client/src/pages/Game/index.tsx
yarn.lock

- uuid, @types/uuid 설치
- uuid로 userName 생성
- 프로필 디폴트 이미지 url로 상수화하여 입력
- 이후 리팩토링 예정

[Feat/chat seperate] 채팅 구분

---

packages/client/src/components/Message/ChatMsg.tsx
packages/client/src/containers/ChatContainer.tsx
packages/client/src/hooks/useChat.ts
packages/client/src/hooks/useTimer.ts
packages/client/src/pages/Game/index.tsx
packages/domain/constants/event.ts
packages/domain/types/chat.ts
packages/server/sockets/chat.ts

<br/>
- `NIGHT_MESSAGE` 통해 `roomName` 받고 해당 `roomName`에 `PUBLISH_MESSAGE` emit
- 클릭 통해 채팅 보내기 onClick() -> handleClick()
- 엔터키 통해 채팅 보내기 handleKeyDown()
- 공통된 채팅 보내는 함수 sendMessage()
- task issues: Resolves #53

[TASK] 밤 채팅 구현

---

.gitignore
packages/server/api/auth/auth.controller.ts
packages/server/api/room/room.controller.ts
packages/server/loaders/db.ts
packages/server/loaders/express.ts
packages/server/package.json
yarn.lock

- server/config/*.config.json에 위치
- db.config.json : DB 관련
- client.config.json : 클라이언트 관련
- github.config.json : 깃헙 OAuth 관련
- task issues: Resolves #78

[REFACTOR] config 파일 설정

---

packages/server/api/auth/auth.controller.ts
packages/server/api/room/room.controller.ts
packages/server/api/user/index.ts
packages/server/api/user/user.controller.ts
packages/server/api/user/user.service.ts
packages/server/loaders/express.ts
packages/server/loaders/router.ts
packages/server/models/Room.ts
packages/server/models/User.ts
packages/server/sockets/game.ts

<br/>
- User 스키마 설정
```
interface IUser extends Document {
userName: string;
profileImg: string;
score: number;
playCnt: number;
jobStat: {
[job: string]: {
killRate: number;
winRate: number;
cnt: number;
winCnt: number;
mvpCnt: number;
};
};
}
```
- User 생성시 `profileImg`, `userName` 필요 (나머지 컬럼 default 값으로 초기화)
- UserController, UserService, userRouter 구현
- 현재 총 플레이 판수, 직업당 플레이 판 수 , 승리 판 수 데이터 업데이트 
- Room 방장 컬럼 삭제
```
interface IRoom extends Document {
roomId: string;
title: string;
}
```
- task issues: Resolves #101

[TASK] 기초 통계 데이터 DB에 저장 및 업데이트 구현

---

packages/client/src/components/Button/AbilityButton.tsx
packages/client/src/containers/LeftSideContainer.tsx
packages/client/src/hooks/useVote.ts
packages/client/src/pages/Game/index.tsx
packages/domain/types/game.ts
packages/domain/types/vote.ts
packages/server/sockets/game.ts
packages/server/sockets/vote.ts
packages/server/stores/GameStore.ts

[TASK] 투표 버그 픽스

---

packages/server/stores/GameStore.ts

<br/><br/>
1. 투표 한번만 하도록 설정
- 서버쪽에서 투표한 사람이 다른 사람을 투표했으면 삭제시키고 새로 투표하도록 구현해서 버그 해결
<br/><br/>
- task issues: Resolves #112

[FIX] 투표 한번만 하도록 설정

---

packages/client/src/pages/Game/index.tsx
packages/domain/constants/time.ts
packages/server/sockets/game.ts
packages/server/sockets/vote.ts

- `viewToast()` 추가
- ms로 돌아가는 함수들에서 사용하기 위해 domain/constants/time.ts에 `SEC` 추가

[REFACTOR} 투표 및 토스트 메세지 리팩토링

---

packages/client/src/pages/GameResult/index.tsx

[TASK] 게임 종료 후 방 나가기 기능

---

packages/client/src/animation/ExecuteAnimation.tsx

[FIX] ExecuteAnimation 이미지 오류 해결

---

packages/client/src/hooks/useChat.ts

- task issues: Resolves #
- considering issues: #

fix: police ability 이벤트 off 추가

---

packages/client/src/hooks/useChat.ts
packages/server/sockets/ability.ts

- task issues: Resolves #
- considering issues: #

[FIX] 아무도 죽지 않았을때 스토리 메세지 보여주지 않게 해결

---

packages/domain/constants/time.ts
packages/server/sockets/game.ts

- DAY_DURATION과 NIGHT_DURATION 변수를 만듬
- counter를 증가시키는게 아니라 감소시키는 형식으로 변경해서 counter를 클라이언트에게 바로 넘겨줌
- task issues: Resolves #138

[TASK] 밤 시간 30초로 변경

---

.gitignore
packages/server/api/room/room.controller.ts
packages/server/error/ApplicationError.ts
packages/server/error/InternalServerError.ts
packages/server/error/InvalidRoomIdError.ts
packages/server/error/errorHandler.ts
packages/server/loaders/errorHandlerLoader.ts
packages/server/loaders/index.ts

[TASK] Express 에러 핸들링

---

packages/server/sockets/ability.ts

<br/><br/>
밤 끝남과 동시에 마피아 능력으로 인해 죽은 피해자 적용되어 게임 끝 판정됨
<br/><br/>
- task issues: Resolves #141

[TASK] 마피아 능력사용 수정

---

packages/server/axios/apiClient.ts
packages/server/error/MethodNotAllowedError.ts
packages/server/loaders/express.ts
packages/server/loaders/router.ts
packages/server/loaders/socket.ts
packages/server/package.json
packages/server/sockets/index.ts
packages/server/stores/RoomStore.ts
yarn.lock

- task issues: Resolves #
- considering issues: #

[FIX] 소켓에서의 API 요청 수정

---

packages/client/src/components/Card/RoomCard.tsx
packages/client/src/containers/RoomContainer.tsx
packages/client/src/containers/RoomFormContainer.tsx
packages/client/src/pages/Waiting/index.tsx
packages/client/src/templates/Header/index.tsx
packages/client/src/types/index.ts
packages/domain/types/room.ts
packages/server/api/room/index.ts
packages/server/api/room/room.controller.ts
packages/server/api/room/room.service.ts

[TASK] 방 생성 기능 추가

---

packages/client/src/components/Card/JobStatCard.tsx
packages/client/src/components/Card/ResultCard.tsx

- task issues: Resolves #
- considering issues: #

fix: job 타입을 domain에 저장된 type으로 변경

---

packages/client/src/components/Card/JobStatCard.tsx
packages/client/src/pages/Profile/index.tsx

[FIX] 플레이 판수 0일시 NaN 예외처리

---

packages/server/models/User.ts

[FIX] 영매 User 스키마에 추가

---

.gitignore
.vscode/settings.json
packages/server/artillery/hooks/index.js
packages/server/artillery/test.yml
packages/server/package.json
yarn.lock

- 결과는 `packages/server/artilery/report` (또는 `/report`)내에 저장해서 .gitignore로 무시하도록 설정했습니당~ 
- YAML에서는 쌍따옴표 써야해서 프리티어 설정 무시하도록 setting 추가했습니다
- `artillery run -o {결과파일경로및이름}.json {스크립트파일경로및이름}.yml` 으로 실행
- `artillery run {스크립트파일경로및이름}.yml` 결과 파일 필요 없고 실행만 할 경우
- `artillery report {결과파일경로및이름}.json` 으로 결과 html 파일 내보내기
- task issues: Resolves #172

[TASK] 부하 테스트 기본 설정

---

packages/client/src/containers/ChatContainer.tsx
packages/client/src/containers/LeftSideContainer.tsx
packages/client/src/containers/ProfileLeftSideContainer.tsx
packages/client/src/containers/RightSideContainer.tsx
packages/client/src/containers/TabContainer.tsx
packages/client/src/lists/AbilityButtonList.tsx
packages/client/src/lists/AchievementListContainer.tsx
packages/client/src/lists/ChatMsgList.tsx
packages/client/src/lists/JobStatContainer.tsx
packages/client/src/lists/MemoList.tsx
packages/client/src/lists/ResultCardList.tsx
packages/client/src/lists/RoomContainer.tsx
packages/client/src/lists/WaitingListContainer.tsx
packages/client/src/pages/GameResult/index.tsx
packages/client/src/pages/Profile/index.tsx
packages/client/src/pages/Rooms/index.tsx
packages/client/src/pages/Waiting/index.tsx

[REFACTOR] 컴포넌트 분리 작업

---

packages/client/src/pages/Profile/index.tsx
packages/client/src/pages/Rooms/index.tsx
packages/client/src/templates/Header/index.tsx
packages/socket/sockets/game.ts
packages/socket/sockets/index.ts
packages/socket/stores/GameStore.ts
packages/socket/stores/RoomStore.ts

<br/><br/>
1. 타이머 버그
- 방 마다의 타이머를 저장해두는 Store를 생성
- 게임이 시작할 때 타이머를 저장
- 사용자가 나갈때마다 체크해서 0명 일 때 타이머 clear
3. 방 나가기 적용 안됨 문제
- 프론트에서 disconnect 이벤트를 안보내주는 문제였다
- 나가기 할 때 `history.goBack()` 을 사용 -> state를 그대로 가져와서 소켓 상태를 그대로 유지 (`true`로 가지고 있는듯) 해서 disconnect이 안되는 것 같음. 하지만 더 찾아봐야해요~
- history.push('/rooms')` 로 수정했더니 disconnect 이벤트 제대로 보냄
- 해결!

[FIX] 플레이어 없을시 타이머 초기화 및 방 나가기 적용 안됨 문제 해결

---

packages/client/src/components/Button/AbilityButton.tsx
packages/client/src/containers/GamePageModalContainer.tsx
packages/client/src/containers/LeftSideContainer.tsx
packages/client/src/hoc/index.tsx
packages/client/src/hooks/useAbility.ts
packages/client/src/hooks/useLog.ts
packages/client/src/lists/AbilityButtonList.tsx
packages/client/src/templates/Header/index.tsx
packages/socket/sockets/game.ts
packages/socket/stores/RoomStore.ts

- [PERFORMANCE] 리액트 최적화, 조건부 렌더링 HOC 패턴 적용

[12.04] 작업 분량

---

.github/workflows/main.yml
README.md

- API 서버와 같은 인스턴스내 컨테이너로 실행 (인스턴스 하나로 구성) -> 두 번째 서버 접속 workflow 삭제
- API 서버 내 deploy.sh 통해서 소켓 서버 컨테이너 돌리도록 변경
- Nginx socket 서버 요청 경로 변경
- 기술 스택 이미지 및 ERD 이미지 최신으로 반영

[FIX] 배포 구성 변경
